[package]
name = "easytab"
version = "0.3.0"
edition = "2024"

description = "A Rust crate built for vendor-agnostic interaction with pen & tablet devices."
license = "MIT"
repository = "https://github.com/DexterHill0/easytab-rs"
keywords = ["tablet", "stylus", "pen", "input", "wacom"]
categories = ["hardware-support", "os::windows-apis"]
exclude = [
    ".github/",
    ".vscode/",
    "release-please-config.json",
    ".release-please-manifest.json",
]
readme = "README.md"

[[example]]
name = "basic"
doc-scrape-examples = true

[package.metadata.docs.rs]
all-features = true
default-target = "x86_64-pc-windows-msvc"
targets = ["x86_64-pc-windows-msvc"]

[dependencies]
thiserror = "2"

raw-window-handle = { version = "0.6", optional = true, features = ["std"] }

[features]
raw-window-handle = ["dep:raw-window-handle"]

[target.'cfg(windows)'.dependencies.windows]
version = "0.62"
features = [
    "Win32_Foundation",
    "Win32_System_Com",
    "Win32_UI_Shell",
    "Win32_UI_WindowsAndMessaging",
    "Win32_UI_Input_Pointer",
]

[target.'cfg(target_os = "macos")'.dependencies]
objc2 = { version = "0.6.4" }
objc2-foundation = { version = "0.3.2", default-features = false }
objc2-app-kit = { version = "0.3.2", default-features = false, features = [
    "NSResponder",
    "NSEvent",
    "NSView",
    "NSWindow",
] }
ctor = "1.0.9"
dtor = "1.0.5"

[dev-dependencies]
easytab = { path = ".", features = ["raw-window-handle"] }
winit = "0.30"
